language: c
group: travis_latest
dist: bionic

git:
  depth: false
  quiet: true

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - libwrap0-dev
    - debhelper

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./configure --listener=systemd,inetd,xinetd --hostname=travis; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./configure --listener=mac --hostname=travis; fi
  - make
  - sudo make install
  - .travis/test.sh
